services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_ADDR: :8080
      NS_MARIADB_USER: root
      NS_MARIADB_PASSWORD: pass
      NS_MARIADB_HOSTNAME: db
      NS_MARIADB_PORT: "3306"
      NS_MARIADB_DATABASE: app
      TRAQ_ORIGIN: ${TRAQ_ORIGIN}
      TRAQ_BOT_TOKEN: ${TRAQ_BOT_TOKEN}
      TRAQ_USER_MANAGER_ID: ${TRAQ_USER_MANAGER_ID:-ramdos}
      CREATE_TICKET_CHANNEL_ID: ${CREATE_TICKET_CHANNEL_ID:-019b3b02-3d31-7439-9069-d28f5de68f47}
      TRAQ_CHANNEL_TICKET_CREATE: ${TRAQ_CHANNEL_TICKET_CREATE:-019b3b02-3d31-7439-9069-d28f5de68f47}
      TRAQ_CHANNEL_TICKET_UPDATE: ${TRAQ_CHANNEL_TICKET_UPDATE:-019b3b02-3d31-7439-9069-d28f5de68f47}
      TRAQ_CHANNEL_NOTE_INCOMING: ${TRAQ_CHANNEL_NOTE_INCOMING:-019b3b02-3d31-7439-9069-d28f5de68f47}
      TRAQ_CHANNEL_NOTE_OUTGOING: ${TRAQ_CHANNEL_NOTE_OUTGOING:-019b3b02-3d31-7439-9069-d28f5de68f47}
      TRAQ_CHANNEL_NOTE_OTHER: ${TRAQ_CHANNEL_NOTE_OTHER:-019b3b02-3d31-7439-9069-d28f5de68f47}
      TRAQ_CHANNEL_REVIEW_NOTIFY: ${TRAQ_CHANNEL_REVIEW_NOTIFY:-019b3b02-3d31-7439-9069-d28f5de68f47}

    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./

  db:
    image: mariadb:latest
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    healthcheck:
      test: mariadb --user=root --password=pass --execute "SHOW DATABASES;"
      interval: 1s
      timeout: 10s
      retries: 30

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy